[project]
name = "polyreco"
version = "0.1.0"
description = "Polyrecognition"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=1.26.0",
    "highspy>=1.0.0",
    "matplotlib>=3.8.0",
    "tqdm>=4.67.3",
]

[project.scripts]
window-line-functions-viewer = "run_window_line_functions_viewer:main"
full-circle-split-viewer = "generate_full_circle_split_cached_viewer:main"
